### PR TITLE
Fixes add map objects

### PR DESCRIPTION
**Pull request by ChristopherSchmidt89**
This should fixes request changes to the display of adding new events, removing a step in between.
Also provides a work-around for browser, who do not cope with datetime-local properly.

### CODE REVIEW

**Comment by mathebox** [comment]
This datetime format of the new tooltip does not match the format displayed in the datetime picker. This can be confusing.

Furthermore the tooltip icon is placed in a separated row (above the datetime picker). For a better UX the icon should be put next to the datetime picker.

screen shot 2017-11-26 at 09 47 32

**Comment by ChristopherSchmidt89** [comment]
Datetime is really an issue with other browsers, e.g. Firefox or Safari they do not support a picker at all, hence their is no predefined format at all. Interestingly they do not accept any other format in these browsers, but in Chrome they propose this dd.mm.yyyy, --:-- externally, probably doing own conversion to the other one in .js (?)

Do you have a good idea how to proceed, either go with the datetime-local input field and hope that eventually the other browsers support this as well, and have the tooltip as a work around
Or go with a different external implementation or own one ... ?

**Comment by mathebox** [comment]
@ChristopherSchmidt89 
The best solution would be to have input field design with Angular Material. But currently they only offer a date picker.
As a workaround I would suggest removing/hiding the tooltip on chrome. Off the top of my head, I would check the user agent. I don't know if there is browser detection built into angular.

**Comment by Bensk1** [comment]
How do we continue from here?

**Pull request merged**
